In [40]:
import pandas as pd
excel_file = '../data/rawdata/EIA-StatetoStateCapacity.xlsx'
MajorPipe_Summary = pd.read_excel(open(excel_file, 'rb'), sheet_name='Major Pipeline Summary', header=0)
MajorPipe_Summary.head(3)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Major Pipeline Crossing Multiple State Borders...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Pipeline,Segment,State From,State To,2018.0,2017.0,2016.0,2015.0,2014.0,2013.0,2012.0,2011.0,2010.0,2009.0,2008.0,2007.0

In [30]:
column_names = MajorPipe_Summary.columns
column_names

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [38]:
#df = (pd.read_excel('UF_AGT702-M.xlsx', skiprows=2, sheetname='Report').dropna(how='all', axis=1))
MajorPipe_Summary = (pd.read_excel(excel_file, skiprows=2, sheet_name='0')
                     .dropna(how='all', axis=1))
MajorPipe_Summary

XLRDError: No sheet named <'0'>

In [37]:
csv_file = '../data/rawdata/EIA_CSV/MajorPipelineSummary.csv'
MajorPipe_Summary1 = pd.read_csv(csv_file, header=0,skip_blank_lines=True)
MajorPipe_Summary1

,Major Pipeline Crossing Multiple State Borders (Capacity in MMcfd),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Pipeline,Segment,State From,State To,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007
2,NaN,Algonquin Gas Trans Co,M1,New Jersey,New York,"1,625","1,532","1,492","1,150","1,150","1,150","1,150","1,150","1,150","1,150","1,150","1,150"
3,NaN,Algonquin Gas Trans Co,M2,New York,Connecticut,"1,830","1,737","1,697","1,355","1,355","1,355","1,355","1,355","1,355","1,355","1,355","1,030"
4,NaN,Algonquin Gas Trans Co,M3,Connecticut,Rhode Island,"1,235","1,142","1,102",760,760,760,760,760,760,760,760,760
5,NaN,Algonquin Gas Trans Co,M4,Rhode Island,Massachusetts,"1,180","1,087","1,047",705,705,705,705,705,705,705,705,705
6,NaN,Algonquin Gas Trans Co,M4 Back,Massachusetts,Rhode Island,275,275,275,275,275,275,275,275,275,0,0,0
7,NaN,Algonquin Gas Trans Co,M3 Back,Rhode Island,Connecticut,275,275,275,275,275,275,275,275,275,0,0,0
8,NaN,Algonquin Gas Trans Co,M2 Back,Connecticut,New York,275,275,275,275,275,275,275,275,275,0,0,0
9,NaN,Algonquin Gas Trans Co,M1 Back,New York,New Jersey,275,275,275,275,275,275,275,275,275,0,0,0
10,NaN,Algonquin Gas Trans Co,Main Line,Max Capacity,NaN,"1,830","1,737","1,697","1,355","1,355","1,355","1,355","1,355","1,355","1,355","1,355","1,150"
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Alliance Pipeline Co,M1,Saskatchewan,North Dakota,"1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875"
13,NaN,Alliance Pipeline Co,M2,North Dakota,Minnesota,"1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875"
14,NaN,Alliance Pipeline Co,M3,Minnesota,Iowa,"1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875"
15,NaN,Alliance Pipeline Co,M4,Iowa,Illinois,"1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875"
16,NaN,Alliance Pipeline Co,Main Line,Max Capacity,NaN,"1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875","1,875"
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,ANR Pipeline Co,GC1,Gulf of Mexico,Louisiana,0,0,0,0,0,0,0,"1,919","1,919","1,919","1,919","1,919"
19,NaN,ANR Pipeline Co,GC2,Louisiana,Arkansas,"1,430","1,430","1,430","1,430","1,430","1,430","1,430","1,430","1,430","1,430","1,430","1,430"
20,NaN,ANR Pipeline Co,GC3,Arkansas,Mississippi,"1,430","1,430","1,430",NaN,"1,430","1,430","1,430","1,430","1,430","1,430","1,430","1,430"
21,NaN,ANR Pipeline Co,GC4,Mississippi,Tennessee,"1,753","1,753","1,753","1,753","1,753","1,753","1,753","1,753","1,753","1,753","1,753","1,753"
22,NaN,ANR Pipeline Co,GC5,Tennessee,Kentucky,"1,398","1,398","1,398","1,398","1,398","1,398","1,398","1,398","1,398","1,398","1,398","1,398"
23,NaN,ANR Pipeline Co,GC6,Kentucky,Indiana,"1,386","1,386","1,386","1,386","1,386","1,386","1,386","1,386","1,386","1,386","1,386","1,386"
24,NaN,ANR Pipeline Co,GC7,Indiana,Ohio,"1,748","1,748","1,748","1,748","1,748","1,748","1,748","1,748","1,748","1,748","1,748","1,748"
25,NaN,ANR Pipeline Co,CG8,Ohio,Michigan,932,932,932,932,932,932,932,932,932,932,932,932
26,NaN,ANR Pipeline Co,CG8 Back,Michigan,Ohio,100,100,100,100,100,100,100,100,100,100,100,100
27,NaN,ANR Pipeline Co,GC7 Back,Ohio,Indiana,452,452,452,452,318,318,318,318,318,318,318,318
28,NaN,ANR Pipeline Co,GC6 Back,Indiana,Kentucky,750,750,750,750,0,0,0,0,0,0,0,0
29,NaN,ANR Pipeline Co,GC5 Back,Kentucky,Tennessee,750,750,750,750,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,NaN,Tuscarora Pipeline Co,M2,California,Nevada,162,162,162,162,162,162,162,162,162,162,162,162
560,NaN,Tuscarora Pipeline Co,Main Line,Max Capacity,NaN,184,184,184,184,184,184,184,184,184,184,184,184
561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
562,NaN,Vector Pipeline Co,M1,Illinois,Indiana,"1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,245","1,245"
563,NaN,Vector Pipeline Co,M2,Indiana,Michigan,"1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,245","1,245"
564,NaN,Vector Pipeline Co,M3,Michigan,Ontario,"1,560","1,560","1,560","1,560","1,560","1,560","1,560","1,560","1,560","1,560","1,245","1,245"
565,NaN,Vector Pipeline Co,M3 Back,Ontario,Michigan,"1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,245","1,245"
566,NaN,Vector Pipeline Co,Main Line,Max Capacity (Eastward ),NaN,"1,560","1,560","1,560","1,560","1,560","1,560","1,560","1,560","1,560","1,560","1,245","1,245"
567,NaN,Vector Pipeline Co,Main Line,Max Capacity (Westward),NaN,"1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,350","1,245","1,245"
568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
569,NaN,Viking Gas Transmission Co,M1,Manitoba,Minnesota,516,516,516,516,516,516,516,516,516,516,516,516
570,NaN,Viking Gas Transmission Co,M2,Minnesota,Wisconsin,437,437,437,437,437,437,437,437,437,437,437,437
571,NaN,Viking Gas Transmission Co,L1,Minnesota,North Dakota,101,101,101,101,101,101,101,101,101,101,63,63
572,NaN,Viking Gas Transmission Co,Main Line,Max Capacity,NaN,516,516,516,516,516,516,516,516,516,516,516,516
573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
574,NaN,WBI Energy Transmission,M1,South Dakota,Wyoming,85,85,85,85,85,85,85,85,85,85,85,85
575,NaN,WBI Energy Transmission,M2,Wyoming,Montana,421,421,421,421,421,421,421,421,421,421,421,380
576,NaN,WBI Energy Transmission,M3,Montana,North Dakota,542,542,542,542,542,542,542,542,542,542,467,426
577,NaN,WBI Energy Transmission,M4,Saskatchewan,North Dakota,46,46,46,46,46,46,46,46,46,46,46,46
578,NaN,WBI Energy Transmission,M5,North Dakota,South Dakota,54,54,54,54,54,54,54,54,54,54,54,54
579,NaN,WBI Energy Transmission,M5 Back,South Dakota,North Dakota,53,53,53,53,53,53,53,53,53,53,53,53
580,NaN,WBI Energy Transmission,M3 Back,North Dakota,Montana,268,268,268,268,268,268,268,268,268,268,268,268
581,NaN,WBI Energy Transmission,M2 Back,Montana,Wyoming,275,275,275,275,275,275,275,275,275,275,275,275
582,NaN,WBI Energy Transmission,M1 Back,Wyoming,South Dakota,27,27,27,27,27,27,27,27,27,27,27,27
583,NaN,WBI Energy Transmission,Main Line,Max Capacity,NaN,542,542,542,542,542,542,542,542,542,542,467,426
584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585,NaN,Wyoming Interstate Co,M1,Utah,Wyoming,586,586,586,586,586,586,586,586,586,406,406,406
586,NaN,Wyoming Interstate Co,M2,Colorado,Wyoming,341,341,341,341,341,341,341,341,341,341,341,341
587,NaN,Wyoming Interstate Co,M3,Wyoming,Colorado,"2,477","2,255","2,255","2,255","2,255","2,255","2,255","2,255","2,255","2,255","2,200","1,870"
588,NaN,Wyoming Interstate Co,Main Line,Max Capacity,NaN,"2,477","2,255","2,255","2,255","2,255","2,255","2,255","2,255","2,255","2,255","2,200","1,870"

In [28]:
column_names1 = MajorPipe_Summary1.columns
column_names1

Index(['Major Pipeline Crossing Multiple State Borders (Capacity in MMcfd)',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [22]:
#df = (pd.read_excel('UF_AGT702-M.xlsx', skiprows=2, sheetname='Report').dropna(how='all', axis=1))