In [2]:
import pandas as pd
excel_file = '../data/rawdata/EIA-StatetoStateCapacity.xlsx'
MajorPipe_Summary = pd.read_excel(excel_file, sheet_name='Major Pipeline Summary', skiprows=4, header=0)
MajorPipe_Summary.head(3)

,Unnamed: 0,Pipeline,Segment,State From,State To,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007
0,NaN,Algonquin Gas Trans Co,M1,New Jersey,New York,1625.0,1532.0,1492.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0
1,NaN,Algonquin Gas Trans Co,M2,New York,Connecticut,1830.0,1737.0,1697.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1030.0
2,NaN,Algonquin Gas Trans Co,M3,Connecticut,Rhode Island,1235.0,1142.0,1102.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0

In [3]:
#df = (pd.read_excel('UF_AGT702-M.xlsx', skiprows=2, sheetname='Report').dropna(how='all', axis=1))
MajorPipe_Summary = MajorPipe_Summary.dropna(how='all', axis=1)
MajorPipe_Summary.head(3)

,Pipeline,Segment,State From,State To,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007
0,Algonquin Gas Trans Co,M1,New Jersey,New York,1625.0,1532.0,1492.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0
1,Algonquin Gas Trans Co,M2,New York,Connecticut,1830.0,1737.0,1697.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1030.0
2,Algonquin Gas Trans Co,M3,Connecticut,Rhode Island,1235.0,1142.0,1102.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0

In [4]:
MajorPipe_Summary = MajorPipe_Summary.dropna(thresh=2, axis=0)
MajorPipe_Summary.head()

,Pipeline,Segment,State From,State To,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007
0,Algonquin Gas Trans Co,M1,New Jersey,New York,1625.0,1532.0,1492.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0
1,Algonquin Gas Trans Co,M2,New York,Connecticut,1830.0,1737.0,1697.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1030.0
2,Algonquin Gas Trans Co,M3,Connecticut,Rhode Island,1235.0,1142.0,1102.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0
3,Algonquin Gas Trans Co,M4,Rhode Island,Massachusetts,1180.0,1087.0,1047.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0
4,Algonquin Gas Trans Co,M4 Back,Massachusetts,Rhode Island,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0

In [5]:
#MajorPipe_Summary2= MajorPipe_Summary.reset_index(drop=True)
#MajorPipe_Summary2

In [6]:
list_index =[]
for index,row in MajorPipe_Summary.iterrows():
    ss = row["State From"]
    if ss[:12] == "Max Capacity":
        print(f"{ss},{index}")
        list_index.append(index)
        
MajorPipe_Summary2 = MajorPipe_Summary.drop(list_index)
MajorPipe_Summary2

Max Capacity,8
Max Capacity,14
Max Capacity (Northward),31
Max Capacity (Southward),32
Max Capacity (Eastward),39
Max Capacity (Westward - Clockwise),48
Max Capacity (Eastward - Counterclockwise),49
Max Capacity,55
Max Capacity (Southward),63
Max Capacity (Northward),64
Max Capacity,79
Max Capacity (Southward),87
Max Capacity (Northward),88
Max Capacity (Eastward),92
Max Capacity (Westward ),93
Max Capacity (West),106
Max Capacity (Eastward ),107
Max Capacity (Eastward ),113
Max Capacity (Westward ),114
Max Capacity,115
Max Capacity (West),126
Max Capacity (West),131
Max Capacity,145
Max Capacity,153
Max Capacity,158
Max Capacity,164
Max Capacity,170
Max Capacity (Eastward),180
Max Capacity (Westward),181
Max Capacity,185
Max Capacity,194
Max Capacity,197
Max Capacity,202
Max Capacity,207
Max Capacity (Northward),213
Max Capacity (Southward),214
Max Capacity,220
Max Capacity (Northward),228
Max Capacity (Southward),229
Max Capacity,240
Max Capacity (Northward),250
Max Capacity (Southward),251
Max Capacity (Northward),255
Max Capacity (Southward),256
Max Capacity (Southward),262
Max Capacity (Northward),263
Max Capacity,272
Max Capacity,289
Max Capacity,305
Max Capacity,306
Max Capacity,318
Max Capacity (Southward),324
Max Capacity (Northward),325
Max Capacity,333
Max Capacity,337
Max Capacity (Eastward ),352
Max Capacity (Westward),353
Max Capacity,357
Max Capacity,362
Max Capacity,366
Max Capacity,370
Max Capacity,380
Max Capacity,390
Max Capacity,402
Max Capacity,406
Max Capacity (Northward),429
Max Capacity (Southward),430
Max Capacity,442
Max Capacity,446
Max Capacity (Northward),464
Max Capacity (Southward),465
Max Capacity,472
Max Capacity,479
Max Capacity (Northward),498
Max Capacity (Southward),499
Max Capacity,505
Max Capacity,509
Max Capacity (Northward),531
Max Capacity (Southward),532
Max Capacity,540
Max Capacity,554
Max Capacity,558
Max Capacity (Eastward ),564
Max Capacity (Westward),565
Max Capacity,570
Max Capacity,581
Max Capacity,586

,Pipeline,Segment,State From,State To,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007
0,Algonquin Gas Trans Co,M1,New Jersey,New York,1625.0,1532.0,1492.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0
1,Algonquin Gas Trans Co,M2,New York,Connecticut,1830.0,1737.0,1697.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1030.0
2,Algonquin Gas Trans Co,M3,Connecticut,Rhode Island,1235.0,1142.0,1102.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0
3,Algonquin Gas Trans Co,M4,Rhode Island,Massachusetts,1180.0,1087.0,1047.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0
4,Algonquin Gas Trans Co,M4 Back,Massachusetts,Rhode Island,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0
5,Algonquin Gas Trans Co,M3 Back,Rhode Island,Connecticut,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0
6,Algonquin Gas Trans Co,M2 Back,Connecticut,New York,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0
7,Algonquin Gas Trans Co,M1 Back,New York,New Jersey,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0
10,Alliance Pipeline Co,M1,Saskatchewan,North Dakota,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0
11,Alliance Pipeline Co,M2,North Dakota,Minnesota,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0
12,Alliance Pipeline Co,M3,Minnesota,Iowa,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0
13,Alliance Pipeline Co,M4,Iowa,Illinois,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0
16,ANR Pipeline Co,GC1,Gulf of Mexico,Louisiana,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1919.0,1919.0,1919.0,1919.0,1919.0
17,ANR Pipeline Co,GC2,Louisiana,Arkansas,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0
18,ANR Pipeline Co,GC3,Arkansas,Mississippi,1430.0,1430.0,1430.0,NaN,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0
19,ANR Pipeline Co,GC4,Mississippi,Tennessee,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0
20,ANR Pipeline Co,GC5,Tennessee,Kentucky,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0
21,ANR Pipeline Co,GC6,Kentucky,Indiana,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0
22,ANR Pipeline Co,GC7,Indiana,Ohio,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0
23,ANR Pipeline Co,CG8,Ohio,Michigan,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0
24,ANR Pipeline Co,CG8 Back,Michigan,Ohio,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
25,ANR Pipeline Co,GC7 Back,Ohio,Indiana,452.0,452.0,452.0,452.0,318.0,318.0,318.0,318.0,318.0,318.0,318.0,318.0
26,ANR Pipeline Co,GC6 Back,Indiana,Kentucky,750.0,750.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,ANR Pipeline Co,GC5 Back,Kentucky,Tennessee,750.0,750.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,ANR Pipeline Co,GC4 Back,Tennessee,Mississippi,1375.0,1375.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,ANR Pipeline Co,GC3 Back,Mississippi,Arkansas,1150.0,1150.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,ANR Pipeline Co,GC2 Back,Arkansas,Louisiana,1150.0,1150.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,ANR Pipeline Co,MC1,Texas,Oklahoma,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0
34,ANR Pipeline Co,MC2,Oklahoma,Kansas,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0
35,ANR Pipeline Co,MC3,Kansas,Nebraska,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,Trunkline Gas Co,M4,Arkansas,Mississippi,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0
546,Trunkline Gas Co,M5,Mississippi,Tennessee,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0
547,Trunkline Gas Co,M6,Tennessee,Kentucky,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0
548,Trunkline Gas Co,M7,Kentucky,Illinois,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0
549,Trunkline Gas Co,M8,Illinois,Indiana,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0
550,Trunkline Gas Co,M9,Indiana,Michigan,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0
551,Trunkline Gas Co,M7 Back,Illinois,Kentucky,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
552,Trunkline Gas Co,M6 Back,Kentucky,Tennessee,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
553,Trunkline Gas Co,M5 Back,Tennessee,Mississippi,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
556,Tuscarora Pipeline Co,M1,Oregon,California,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0
557,Tuscarora Pipeline Co,M2,California,Nevada,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0
560,Vector Pipeline Co,M1,Illinois,Indiana,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1245.0,1245.0
561,Vector Pipeline Co,M2,Indiana,Michigan,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1245.0,1245.0
562,Vector Pipeline Co,M3,Michigan,Ontario,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1245.0,1245.0
563,Vector Pipeline Co,M3 Back,Ontario,Michigan,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1245.0,1245.0
567,Viking Gas Transmission Co,M1,Manitoba,Minnesota,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0
568,Viking Gas Transmission Co,M2,Minnesota,Wisconsin,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0
569,Viking Gas Transmission Co,L1,Minnesota,North Dakota,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0,63.0,63.0
572,WBI Energy Transmission,M1,South Dakota,Wyoming,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0
573,WBI Energy Transmission,M2,Wyoming,Montana,421.0,421.0,421.0,421.0,421.0,421.0,421.0,421.0,421.0,421.0,421.0,380.0
574,WBI Energy Transmission,M3,Montana,North Dakota,542.0,542.0,542.0,542.0,542.0,542.0,542.0,542.0,542.0,542.0,467.0,426.0
575,WBI Energy Transmission,M4,Saskatchewan,North Dakota,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0
576,WBI Energy Transmission,M5,North Dakota,South Dakota,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0
577,WBI Energy Transmission,M5 Back,South Dakota,North Dakota,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0
578,WBI Energy Transmission,M3 Back,North Dakota,Montana,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0
579,WBI Energy Transmission,M2 Back,Montana,Wyoming,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0
580,WBI Energy Transmission,M1 Back,Wyoming,South Dakota,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0
583,Wyoming Interstate Co,M1,Utah,Wyoming,586.0,586.0,586.0,586.0,586.0,586.0,586.0,586.0,586.0,406.0,406.0,406.0
584,Wyoming Interstate Co,M2,Colorado,Wyoming,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0
585,Wyoming Interstate Co,M3,Wyoming,Colorado,2477.0,2255.0,2255.0,2255.0,2255.0,2255.0,2255.0,2255.0,2255.0,2255.0,2200.0,1870.0

In [7]:
MajorPipe_Summary3= MajorPipe_Summary2.reset_index(drop=True)
MajorPipe_Summary3

,Pipeline,Segment,State From,State To,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007
0,Algonquin Gas Trans Co,M1,New Jersey,New York,1625.0,1532.0,1492.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0,1150.0
1,Algonquin Gas Trans Co,M2,New York,Connecticut,1830.0,1737.0,1697.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1355.0,1030.0
2,Algonquin Gas Trans Co,M3,Connecticut,Rhode Island,1235.0,1142.0,1102.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0,760.0
3,Algonquin Gas Trans Co,M4,Rhode Island,Massachusetts,1180.0,1087.0,1047.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0,705.0
4,Algonquin Gas Trans Co,M4 Back,Massachusetts,Rhode Island,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0
5,Algonquin Gas Trans Co,M3 Back,Rhode Island,Connecticut,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0
6,Algonquin Gas Trans Co,M2 Back,Connecticut,New York,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0
7,Algonquin Gas Trans Co,M1 Back,New York,New Jersey,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,0.0,0.0,0.0
8,Alliance Pipeline Co,M1,Saskatchewan,North Dakota,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0
9,Alliance Pipeline Co,M2,North Dakota,Minnesota,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0
10,Alliance Pipeline Co,M3,Minnesota,Iowa,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0
11,Alliance Pipeline Co,M4,Iowa,Illinois,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0,1875.0
12,ANR Pipeline Co,GC1,Gulf of Mexico,Louisiana,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1919.0,1919.0,1919.0,1919.0,1919.0
13,ANR Pipeline Co,GC2,Louisiana,Arkansas,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0
14,ANR Pipeline Co,GC3,Arkansas,Mississippi,1430.0,1430.0,1430.0,NaN,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0
15,ANR Pipeline Co,GC4,Mississippi,Tennessee,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0,1753.0
16,ANR Pipeline Co,GC5,Tennessee,Kentucky,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0,1398.0
17,ANR Pipeline Co,GC6,Kentucky,Indiana,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0,1386.0
18,ANR Pipeline Co,GC7,Indiana,Ohio,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0,1748.0
19,ANR Pipeline Co,CG8,Ohio,Michigan,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0,932.0
20,ANR Pipeline Co,CG8 Back,Michigan,Ohio,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
21,ANR Pipeline Co,GC7 Back,Ohio,Indiana,452.0,452.0,452.0,452.0,318.0,318.0,318.0,318.0,318.0,318.0,318.0,318.0
22,ANR Pipeline Co,GC6 Back,Indiana,Kentucky,750.0,750.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,ANR Pipeline Co,GC5 Back,Kentucky,Tennessee,750.0,750.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,ANR Pipeline Co,GC4 Back,Tennessee,Mississippi,1375.0,1375.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,ANR Pipeline Co,GC3 Back,Mississippi,Arkansas,1150.0,1150.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,ANR Pipeline Co,GC2 Back,Arkansas,Louisiana,1150.0,1150.0,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,ANR Pipeline Co,MC1,Texas,Oklahoma,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0,580.0
28,ANR Pipeline Co,MC2,Oklahoma,Kansas,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0,853.0
29,ANR Pipeline Co,MC3,Kansas,Nebraska,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0,693.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,Trunkline Gas Co,M4,Arkansas,Mississippi,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0,1598.0
416,Trunkline Gas Co,M5,Mississippi,Tennessee,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0,1580.0
417,Trunkline Gas Co,M6,Tennessee,Kentucky,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0,1570.0
418,Trunkline Gas Co,M7,Kentucky,Illinois,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0,1544.0
419,Trunkline Gas Co,M8,Illinois,Indiana,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0,745.0
420,Trunkline Gas Co,M9,Indiana,Michigan,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0,739.0
421,Trunkline Gas Co,M7 Back,Illinois,Kentucky,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
422,Trunkline Gas Co,M6 Back,Kentucky,Tennessee,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
423,Trunkline Gas Co,M5 Back,Tennessee,Mississippi,750.0,750.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
424,Tuscarora Pipeline Co,M1,Oregon,California,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0,184.0
425,Tuscarora Pipeline Co,M2,California,Nevada,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0,162.0
426,Vector Pipeline Co,M1,Illinois,Indiana,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1245.0,1245.0
427,Vector Pipeline Co,M2,Indiana,Michigan,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1245.0,1245.0
428,Vector Pipeline Co,M3,Michigan,Ontario,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1560.0,1245.0,1245.0
429,Vector Pipeline Co,M3 Back,Ontario,Michigan,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1350.0,1245.0,1245.0
430,Viking Gas Transmission Co,M1,Manitoba,Minnesota,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0,516.0
431,Viking Gas Transmission Co,M2,Minnesota,Wisconsin,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0,437.0
432,Viking Gas Transmission Co,L1,Minnesota,North Dakota,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0,63.0,63.0
433,WBI Energy Transmission,M1,South Dakota,Wyoming,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0
434,WBI Energy Transmission,M2,Wyoming,Montana,421.0,421.0,421.0,421.0,421.0,421.0,421.0,421.0,421.0,421.0,421.0,380.0
435,WBI Energy Transmission,M3,Montana,North Dakota,542.0,542.0,542.0,542.0,542.0,542.0,542.0,542.0,542.0,542.0,467.0,426.0
436,WBI Energy Transmission,M4,Saskatchewan,North Dakota,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0,46.0
437,WBI Energy Transmission,M5,North Dakota,South Dakota,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0,54.0
438,WBI Energy Transmission,M5 Back,South Dakota,North Dakota,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0
439,WBI Energy Transmission,M3 Back,North Dakota,Montana,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0
440,WBI Energy Transmission,M2 Back,Montana,Wyoming,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0,275.0
441,WBI Energy Transmission,M1 Back,Wyoming,South Dakota,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0
442,Wyoming Interstate Co,M1,Utah,Wyoming,586.0,586.0,586.0,586.0,586.0,586.0,586.0,586.0,586.0,406.0,406.0,406.0
443,Wyoming Interstate Co,M2,Colorado,Wyoming,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0,341.0
444,Wyoming Interstate Co,M3,Wyoming,Colorado,2477.0,2255.0,2255.0,2255.0,2255.0,2255.0,2255.0,2255.0,2255.0,2255.0,2200.0,1870.0

In [8]:
#column_names = MajorPipe_Summary.columns
#column_names

In [9]:
#MajorPipe_Summary.dtypes

In [10]:
#MajorPipe_Summary.count()
#state to has several incomplete rows

In [19]:
MajorPipe_Summary3.to_csv('../data/cleandata/MajorPipe_Summaryda.csv', index=False)

# Inflow_Region

In [12]:
Inflow_Region = pd.read_excel(excel_file, sheet_name='Inflow By Region', skiprows=4, header=0)
Inflow_Region.head()

,Region To,Region From,2018,2017,2016,2015,2014,2013,2012,2011,...,2002,2001,2000,1999,1998,1997,1996,1995,1994,1990
0,Canada,Midwest,4935,4935,4935,4935,4935.0,4935.0,4935.0,4935.0,...,3662.0,3382.0,3382.0,1180.0,1180.0,1180.0,1180.0,1030.0,530.0,0.0
1,NaN,Northeast,2099,2099,2099,2099,1819.0,1819.0,1819.0,1499.0,...,515.0,515.0,415.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,NaN,Mountain,111,81,81,81,81.0,81.0,81.0,81.0,...,81.0,81.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0,NaN
3,NaN,Pacific,51,51,51,51,51.0,51.0,51.0,51.0,...,51.0,51.0,51.0,51.0,0.0,0.0,0.0,0.0,0.0,NaN
4,Canada Total,NaN,7196,7166,7166,7166,6886.0,6886.0,6886.0,6566.0,...,4309.0,4029.0,3914.0,1297.0,1246.0,1246.0,1246.0,1096.0,596.0,0.0

In [13]:
#specify a forward-fill to propagate the previous value forward:
Inflow_Region['Region To'] = Inflow_Region['Region To'].ffill()
Inflow_Region.head()

,Region To,Region From,2018,2017,2016,2015,2014,2013,2012,2011,...,2002,2001,2000,1999,1998,1997,1996,1995,1994,1990
0,Canada,Midwest,4935,4935,4935,4935,4935.0,4935.0,4935.0,4935.0,...,3662.0,3382.0,3382.0,1180.0,1180.0,1180.0,1180.0,1030.0,530.0,0.0
1,Canada,Northeast,2099,2099,2099,2099,1819.0,1819.0,1819.0,1499.0,...,515.0,515.0,415.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,Canada,Mountain,111,81,81,81,81.0,81.0,81.0,81.0,...,81.0,81.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0,NaN
3,Canada,Pacific,51,51,51,51,51.0,51.0,51.0,51.0,...,51.0,51.0,51.0,51.0,0.0,0.0,0.0,0.0,0.0,NaN
4,Canada Total,NaN,7196,7166,7166,7166,6886.0,6886.0,6886.0,6566.0,...,4309.0,4029.0,3914.0,1297.0,1246.0,1246.0,1246.0,1096.0,596.0,0.0

In [14]:
Inflow_Region_filled = Inflow_Region.fillna(0)
Inflow_Region_filled.head()
#Remove Country total rows

,Region To,Region From,2018,2017,2016,2015,2014,2013,2012,2011,...,2002,2001,2000,1999,1998,1997,1996,1995,1994,1990
0,Canada,Midwest,4935,4935,4935,4935,4935.0,4935.0,4935.0,4935.0,...,3662.0,3382.0,3382.0,1180.0,1180.0,1180.0,1180.0,1030.0,530.0,0.0
1,Canada,Northeast,2099,2099,2099,2099,1819.0,1819.0,1819.0,1499.0,...,515.0,515.0,415.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Canada,Mountain,111,81,81,81,81.0,81.0,81.0,81.0,...,81.0,81.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0,0.0
3,Canada,Pacific,51,51,51,51,51.0,51.0,51.0,51.0,...,51.0,51.0,51.0,51.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Canada Total,0,7196,7166,7166,7166,6886.0,6886.0,6886.0,6566.0,...,4309.0,4029.0,3914.0,1297.0,1246.0,1246.0,1246.0,1096.0,596.0,0.0

In [ ]:
#Inflow_Region.columns

In [ ]:
#Inflow_Region.count()
#Region To has several incomplete rows

In [ ]:
#2015-2018 values are in integer form. Check if needed to be converted into float values
#non-null count drops from 38 (2015-2018) to 37 (2014-1994) and to 12 (1990)
#Inflow_Region.dtypes
#Inflow_Region.info()

In [ ]:
#Inflow_Region.rename(columns={'Region To':'Sum Capacity (mmcfd) Region To'}, inplace = True)
#Inflow_Region.head()

In [ ]:
#ss = Inflow_Region[Inflow_Region.loc[:,"Region To"]=="Canada Total"]["Region To"]
#sss=ss.iloc[0]
#sss[-5:]

In [15]:
list_index =[]
for index,row in Inflow_Region.iterrows():
    ss = row["Region To"]
    if ss[-5:] == "Total":
        print(f"{ss},{index}")
        list_index.append(index)
        
Inflow_Region_filled2 = Inflow_Region_filled.drop(list_index)
Inflow_Region_filled2.head()

Canada Total,4
Mexico Total,8
Midwest Total,14
Northeast Total,18
Southeast Total,22
Mountain Total,27
South Central Total,33
Pacific Total,37

,Region To,Region From,2018,2017,2016,2015,2014,2013,2012,2011,...,2002,2001,2000,1999,1998,1997,1996,1995,1994,1990
0,Canada,Midwest,4935,4935,4935,4935,4935.0,4935.0,4935.0,4935.0,...,3662.0,3382.0,3382.0,1180.0,1180.0,1180.0,1180.0,1030.0,530.0,0.0
1,Canada,Northeast,2099,2099,2099,2099,1819.0,1819.0,1819.0,1499.0,...,515.0,515.0,415.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Canada,Mountain,111,81,81,81,81.0,81.0,81.0,81.0,...,81.0,81.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0,0.0
3,Canada,Pacific,51,51,51,51,51.0,51.0,51.0,51.0,...,51.0,51.0,51.0,51.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Mexico,Mountain,713,713,713,690,690.0,489.0,489.0,251.0,...,251.0,242.0,112.0,112.0,34.0,34.0,34.0,34.0,34.0,0.0

In [18]:
Inflow_Region_filled2.to_csv('../data/cleandata/Inflow_Region_filled.csv', index=False)

# Outflow_Region_capacity

In [ ]:
Outflow_Region_capacity = pd.read_excel(excel_file, sheet_name='Outflow By Region', skiprows=4, header=0)
Outflow_Region_capacity.head()

In [ ]:
#specify a forward-fill to propagate the previous value forward:
Outflow_Region_capacity['Region From'] = Outflow_Region_capacity['Region From'].ffill()
Outflow_Region_capacity.head()

In [ ]:
Outflow_Region_capacity = Outflow_Region_capacity.fillna(0)
Outflow_Region_capacity.head ()

In [ ]:
list_index =[]
for index,row in Outflow_Region_capacity.iterrows():
    ss = row["Region From"]
    if ss[-5:] == "Total":
        print(f"{ss},{index}")
        list_index.append(index)
        
Outflow_Region_capacity2 = Outflow_Region_capacity.drop(list_index)
Outflow_Region_capacity2.head()

In [ ]:
#Outflow_Region_capacity.info()

In [20]:
Inflow_Region_filled2.to_csv('../data/cleandata/Outflow_Region_capacity.csv', index=False)

# RegionToRegion_capacity

In [ ]:
RegionToRegion_capacity = pd.read_excel(excel_file, sheet_name='Region to Region Capacity Map', skiprows=1, header=0)
RegionToRegion_capacity.head()

In [ ]:
#RegionToRegion_capacity.columns

In [ ]:
#Only drop columns which have at least 50% non-NaNs
RegionToRegion_capacity = RegionToRegion_capacity.dropna(thresh=int(RegionToRegion_capacity.shape[0]*.5),axis=1)
RegionToRegion_capacity.head(10)
#Check if row with NaN needs to be dropped

In [ ]:
#RegionToRegion_capacity.info()

In [21]:
RegionToRegion_capacity.to_csv('../data/cleandata/#RegionToRegion_capacity.csv', index=False)

NameError: name 'RegionToRegion_capacity' is not defined

# StateInflow_capacity

In [ ]:
StateInflow_capacity = pd.read_excel(excel_file, sheet_name='Inflow By State', skiprows=4, header=0)
StateInflow_capacity.head()

In [ ]:
#specify a forward-fill to propagate the previous value forward:
StateInflow_capacity['State To'] = StateInflow_capacity['State To'].ffill()
StateInflow_capacity.head()

In [ ]:
#There is a lot of non-null variance from year to year
#StateInflow_capacity.info()

In [ ]:
StateOutflow_capacity = pd.read_excel(excel_file, sheet_name='Outflow By State', skiprows=4, header=0)
StateOutflow_capacity.head()

In [ ]:
#specify a forward-fill to propagate the previous value forward:
StateOutflow_capacity['State From'] = StateOutflow_capacity['State From'].ffill()
StateOutflow_capacity.head()

In [ ]:
StateOutflow_capacity = StateOutflow_capacity.fillna(0)
StateOutflow_capacity.head()

In [ ]:
list_index =[]
for index,row in StateOutflow_capacity.iterrows():
    ss = row["State From"]
    if ss[-5:] == "Total":
        print(f"{ss},{index}")
        list_index.append(index)
        
StateOutflow_capacity2 = StateOutflow_capacity.drop(list_index)
StateOutflow_capacity2.head()

In [ ]:
#StateOutflow_capacity.info()

In [ ]:
StateOutflow_capacity2.to_csv('../data/cleandata/StateOutflow_capacity.csv')

# InflowFrom_state_pipeline

In [ ]:
InflowFrom_state_pipeline = pd.read_excel(excel_file, sheet_name='Inflow By State and Pipeline', skiprows=4, header=0)
InflowFrom_state_pipeline.head()

In [ ]:
InflowFrom_state_pipeline = InflowFrom_state_pipeline.fillna(0)
InflowFrom_state_pipeline.head()

In [ ]:
InflowFrom_state_pipeline.to_csv('../data/cleandata/InflowFrom_state_pipeline.csv')

# OutflowFrom_state_pipeline

In [ ]:
OutflowFrom_state_pipeline = pd.read_excel(excel_file, sheet_name='Outflow By State and Pipeline', skiprows=4, header=0)
OutflowFrom_state_pipeline.head()

In [ ]:
OutflowFrom_state_pipeline = OutflowFrom_state_pipeline.fillna(0)
OutflowFrom_state_pipeline.head()

In [ ]:
OutflowFrom_state_pipeline.to_csv('../data/cleandata/OutflowFrom_state_pipeline.csv')

# Regions

In [ ]:
Regions = pd.read_excel(excel_file, sheet_name='Regions', skiprows=1, header=0)
Regions.head()

In [ ]:
#Only drop columns which have at least 50% non-NaNs
Regions = Regions.dropna(thresh=int(Regions.shape[0]*.5),axis=1)
Regions.head()

In [ ]:
Regions.to_csv('../data/cleandata/Regions.csv')

# Pipelines_State2State

In [ ]:
Pipelines_State2State = pd.read_excel(excel_file, sheet_name='Pipeline State2State Capacity', skiprows=1, header=0)
Pipelines_State2State.head()

In [ ]:
Pipelines_State2State = Pipelines_State2State.fillna("")
Pipelines_State2State.head()

In [ ]:
Pipelines_State2State.to_csv('../data/cleandata/Pipelines_State2State.csv')